/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArcadiaConnectPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  peopleFolder: "People/",
  triggerChar: "@",
  showHoverCard: true,
  autoCreatePerson: true,
  licenseKey: "",
  isPro: false
};
var VIEW_TYPE_PEOPLE = "arcadia-connect-people";
var PERSON_NOTE_TEMPLATE = `---
type: person
name: "{{name}}"
email: ""
phone: ""
organization: ""
role: ""
birthday: ""
relationship-type: ""
tags: []
---

# {{name}}

## About

## Interaction Log
`;

// src/settings.ts
var import_obsidian = require("obsidian");
var ArcadiaConnectSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Arcadia Connect Settings" });
    new import_obsidian.Setting(containerEl).setName("People folder").setDesc("Folder where person notes are stored (relative to vault root).").addText((text) => text.setPlaceholder("People/").setValue(this.plugin.settings.peopleFolder).onChange(async (value) => {
      this.plugin.settings.peopleFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Trigger character").setDesc("Character that triggers the @-mention autocomplete.").addText((text) => text.setPlaceholder("@").setValue(this.plugin.settings.triggerChar).onChange(async (value) => {
      this.plugin.settings.triggerChar = value || "@";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show hover card").setDesc("Show a mini profile card when hovering over @-mentions.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showHoverCard).onChange(async (value) => {
      this.plugin.settings.showHoverCard = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-create person note").setDesc("Automatically create a person note when mentioning someone new.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoCreatePerson).onChange(async (value) => {
      this.plugin.settings.autoCreatePerson = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "License" });
    new import_obsidian.Setting(containerEl).setName("License key").setDesc("Enter your Arcadia Connect Pro license key.").addText((text) => text.setPlaceholder("Enter license key").setValue(this.plugin.settings.licenseKey).onChange(async (value) => {
      this.plugin.settings.licenseKey = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/person-manager.ts
var import_obsidian2 = require("obsidian");
var PersonManager = class {
  constructor(app, peopleFolder) {
    this.people = /* @__PURE__ */ new Map();
    this.app = app;
    this.peopleFolder = peopleFolder;
  }
  setPeopleFolder(folder) {
    this.peopleFolder = folder;
  }
  async initialize() {
    await this.scanPeopleFolder();
  }
  async scanPeopleFolder() {
    this.people.clear();
    const folderPath = (0, import_obsidian2.normalizePath)(this.peopleFolder);
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder || !(folder instanceof import_obsidian2.TFolder)) {
      return;
    }
    const files = folder.children.filter(
      (f) => f instanceof import_obsidian2.TFile && f.extension === "md"
    );
    for (const file of files) {
      const person = this.parsePersonFile(file);
      if (person) {
        this.people.set(person.name.toLowerCase(), person);
      }
    }
  }
  parsePersonFile(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    if (!(cache == null ? void 0 : cache.frontmatter)) {
      return null;
    }
    const fm = cache.frontmatter;
    if (fm.type !== "person") {
      return null;
    }
    const name = fm.name || file.basename;
    if (!name) {
      return null;
    }
    return {
      file,
      name: String(name),
      email: fm.email ? String(fm.email) : void 0,
      phone: fm.phone ? String(fm.phone) : void 0,
      organization: fm.organization ? String(fm.organization) : void 0,
      role: fm.role ? String(fm.role) : void 0,
      birthday: fm.birthday ? String(fm.birthday) : void 0,
      relationshipType: fm["relationship-type"] ? String(fm["relationship-type"]) : void 0,
      tags: Array.isArray(fm.tags) ? fm.tags.map(String) : void 0,
      photo: fm.photo ? String(fm.photo) : void 0
    };
  }
  getAllPeople() {
    return Array.from(this.people.values());
  }
  getPersonByName(name) {
    return this.people.get(name.toLowerCase());
  }
  searchPeople(query) {
    if (!query) {
      return this.getAllPeople();
    }
    const lower = query.toLowerCase();
    return this.getAllPeople().filter((p) => {
      return p.name.toLowerCase().includes(lower) || p.organization && p.organization.toLowerCase().includes(lower) || p.tags && p.tags.some((t) => t.toLowerCase().includes(lower));
    });
  }
  fuzzyMatch(query) {
    if (!query) {
      return this.getAllPeople();
    }
    const lower = query.toLowerCase();
    return this.getAllPeople().map((p) => ({
      person: p,
      score: this.fuzzyScore(p.name.toLowerCase(), lower)
    })).filter((r) => r.score > 0).sort((a, b) => b.score - a.score).map((r) => r.person);
  }
  fuzzyScore(target, query) {
    let score = 0;
    let qi = 0;
    let consecutive = 0;
    for (let ti = 0; ti < target.length && qi < query.length; ti++) {
      if (target[ti] === query[qi]) {
        score += 1 + consecutive;
        consecutive++;
        qi++;
      } else {
        consecutive = 0;
      }
    }
    if (qi < query.length) {
      return 0;
    }
    if (target.startsWith(query)) {
      score += 10;
    }
    return score;
  }
  async createPersonNote(name) {
    const folderPath = (0, import_obsidian2.normalizePath)(this.peopleFolder);
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
    const content = PERSON_NOTE_TEMPLATE.replace(/\{\{name\}\}/g, name);
    const filePath = (0, import_obsidian2.normalizePath)(`${this.peopleFolder}/${name}.md`);
    const file = await this.app.vault.create(filePath, content);
    const person = {
      file,
      name
    };
    this.people.set(name.toLowerCase(), person);
    return file;
  }
  updatePerson(file) {
    const person = this.parsePersonFile(file);
    if (person) {
      this.people.set(person.name.toLowerCase(), person);
    }
  }
  removePerson(file) {
    for (const [key, person] of this.people.entries()) {
      if (person.file.path === file.path) {
        this.people.delete(key);
        break;
      }
    }
  }
  isInPeopleFolder(file) {
    const folderPath = (0, import_obsidian2.normalizePath)(this.peopleFolder);
    return file.path.startsWith(folderPath);
  }
};

// src/mention-scanner.ts
var import_obsidian3 = require("obsidian");
var MentionScanner = class {
  constructor(app, peopleFolder) {
    this.mentionIndex = /* @__PURE__ */ new Map();
    this.app = app;
    this.peopleFolder = peopleFolder;
  }
  setPeopleFolder(folder) {
    this.peopleFolder = folder;
  }
  async buildIndex() {
    this.mentionIndex.clear();
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      if (this.isInPeopleFolder(file))
        continue;
      await this.scanFile(file);
    }
  }
  async scanFile(file) {
    this.removeFileFromIndex(file);
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache)
      return;
    const peoplePath = (0, import_obsidian3.normalizePath)(this.peopleFolder);
    if (cache.links) {
      for (const link of cache.links) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(
          link.link,
          file.path
        );
        if (resolved && resolved.path.startsWith(peoplePath)) {
          this.addMention(resolved.basename, file, link.position.start.line);
        }
      }
    }
    if (cache.embeds) {
      for (const embed of cache.embeds) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(
          embed.link,
          file.path
        );
        if (resolved && resolved.path.startsWith(peoplePath)) {
          this.addMention(resolved.basename, file, embed.position.start.line);
        }
      }
    }
  }
  addMention(personName, noteFile, line) {
    const key = personName.toLowerCase();
    if (!this.mentionIndex.has(key)) {
      this.mentionIndex.set(key, []);
    }
    const fileDate = this.extractDateFromFile(noteFile);
    this.mentionIndex.get(key).push({
      personName,
      noteFile,
      noteName: noteFile.basename,
      line,
      date: fileDate
    });
  }
  extractDateFromFile(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.date) {
      return String(cache.frontmatter.date);
    }
    const dateMatch = file.basename.match(/(\d{4}-\d{2}-\d{2})/);
    if (dateMatch) {
      return dateMatch[1];
    }
    return new Date(file.stat.mtime).toISOString().slice(0, 10);
  }
  removeFileFromIndex(file) {
    for (const [key, mentions] of this.mentionIndex.entries()) {
      const filtered = mentions.filter((m) => m.noteFile.path !== file.path);
      if (filtered.length === 0) {
        this.mentionIndex.delete(key);
      } else {
        this.mentionIndex.set(key, filtered);
      }
    }
  }
  getMentionsForPerson(personName) {
    const key = personName.toLowerCase();
    return this.mentionIndex.get(key) || [];
  }
  getRecentMentions(personName, limit = 10) {
    const mentions = this.getMentionsForPerson(personName);
    return mentions.sort((a, b) => b.date.localeCompare(a.date)).slice(0, limit);
  }
  getMentionCount(personName) {
    return this.getMentionsForPerson(personName).length;
  }
  getLastMentionDate(personName) {
    const mentions = this.getMentionsForPerson(personName);
    if (mentions.length === 0)
      return null;
    return mentions.map((m) => m.date).sort().reverse()[0];
  }
  isInPeopleFolder(file) {
    const folderPath = (0, import_obsidian3.normalizePath)(this.peopleFolder);
    return file.path.startsWith(folderPath);
  }
  onFileChange(file) {
    if (!this.isInPeopleFolder(file)) {
      this.scanFile(file);
    }
  }
  onFileDelete(file) {
    this.removeFileFromIndex(file);
  }
};

// src/mention-postprocessor.ts
var MentionPostProcessor = class {
  constructor(app, personManager, settings, profileCard) {
    this.app = app;
    this.personManager = personManager;
    this.settings = settings;
    this.profileCard = profileCard;
  }
  getProcessor() {
    return (el, ctx) => {
      this.processElement(el);
    };
  }
  processElement(el) {
    const trigger = this.settings.triggerChar || "@";
    const walker = document.createTreeWalker(
      el,
      NodeFilter.SHOW_TEXT,
      {
        acceptNode: (node2) => {
          const parent = node2.parentElement;
          if (!parent)
            return NodeFilter.FILTER_REJECT;
          if (parent.tagName === "A" || parent.closest("a") || parent.classList.contains("arcadia-connect-mention")) {
            return NodeFilter.FILTER_REJECT;
          }
          if (node2.textContent && node2.textContent.includes(trigger)) {
            return NodeFilter.FILTER_ACCEPT;
          }
          return NodeFilter.FILTER_REJECT;
        }
      }
    );
    const textNodes = [];
    let node;
    while (node = walker.nextNode()) {
      textNodes.push(node);
    }
    for (const textNode of textNodes) {
      this.processMentionsInText(textNode, trigger);
    }
  }
  processMentionsInText(textNode, trigger) {
    const text = textNode.textContent;
    if (!text)
      return;
    const escapedTrigger = trigger.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(
      `(?:^|(?<=\\s|[([{,;:!?]))${escapedTrigger}([A-Z][a-zA-Z]*(?:\\s[A-Z][a-zA-Z]*)*)`,
      "g"
    );
    const matches = [];
    let match;
    while ((match = regex.exec(text)) !== null) {
      const name = match[1];
      const person = this.personManager.getPersonByName(name);
      if (person) {
        matches.push({
          index: match.index,
          fullMatch: match[0],
          name
        });
      }
    }
    if (matches.length === 0)
      return;
    const parent = textNode.parentNode;
    if (!parent)
      return;
    const fragment = document.createDocumentFragment();
    let lastIndex = 0;
    for (const m of matches) {
      if (m.index > lastIndex) {
        fragment.appendChild(
          document.createTextNode(text.slice(lastIndex, m.index))
        );
      }
      const span = document.createElement("span");
      span.className = "arcadia-connect-mention";
      span.textContent = m.fullMatch;
      span.setAttribute("data-person-name", m.name);
      span.addEventListener("click", (e) => {
        e.preventDefault();
        const person = this.personManager.getPersonByName(m.name);
        if (person) {
          this.app.workspace.openLinkText(person.file.path, "", false);
        }
      });
      if (this.settings.showHoverCard) {
        span.addEventListener("mouseenter", (e) => {
          const person = this.personManager.getPersonByName(m.name);
          if (person) {
            this.profileCard.show(person, span);
          }
        });
        span.addEventListener("mouseleave", () => {
          this.profileCard.scheduleHide();
        });
      }
      fragment.appendChild(span);
      lastIndex = m.index + m.fullMatch.length;
    }
    if (lastIndex < text.length) {
      fragment.appendChild(document.createTextNode(text.slice(lastIndex)));
    }
    parent.replaceChild(fragment, textNode);
  }
};

// src/profile-card.ts
var ProfileCard = class {
  constructor(app) {
    this.cardEl = null;
    this.hideTimeout = null;
    this.app = app;
  }
  show(person, anchor) {
    this.cancelHide();
    this.hide();
    const card = document.createElement("div");
    card.className = "arcadia-connect-profile-card";
    const header = card.createDiv({ cls: "arcadia-connect-card-header" });
    const icon = header.createSpan({ cls: "arcadia-connect-card-icon" });
    icon.textContent = "\u{1F464}";
    header.createEl("strong", { text: person.name });
    const details = card.createDiv({ cls: "arcadia-connect-card-details" });
    if (person.organization) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Org" });
      row.createSpan({ text: person.organization });
    }
    if (person.role) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Role" });
      row.createSpan({ text: person.role });
    }
    if (person.email) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Email" });
      row.createSpan({ text: person.email });
    }
    if (person.phone) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Phone" });
      row.createSpan({ text: person.phone });
    }
    if (person.relationshipType) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Type" });
      row.createSpan({ text: person.relationshipType });
    }
    const footer = card.createDiv({ cls: "arcadia-connect-card-footer" });
    const openBtn = footer.createEl("button", {
      cls: "arcadia-connect-card-open-btn",
      text: "Open"
    });
    openBtn.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.app.workspace.openLinkText(person.file.path, "", false);
      this.hide();
    });
    document.body.appendChild(card);
    this.cardEl = card;
    const anchorRect = anchor.getBoundingClientRect();
    const cardRect = card.getBoundingClientRect();
    let top = anchorRect.bottom + 4;
    let left = anchorRect.left;
    if (top + cardRect.height > window.innerHeight) {
      top = anchorRect.top - cardRect.height - 4;
    }
    if (left + cardRect.width > window.innerWidth) {
      left = window.innerWidth - cardRect.width - 8;
    }
    if (left < 0)
      left = 8;
    card.style.top = `${top}px`;
    card.style.left = `${left}px`;
    card.addEventListener("mouseenter", () => {
      this.cancelHide();
    });
    card.addEventListener("mouseleave", () => {
      this.scheduleHide();
    });
  }
  scheduleHide() {
    this.cancelHide();
    this.hideTimeout = setTimeout(() => {
      this.hide();
    }, 300);
  }
  cancelHide() {
    if (this.hideTimeout) {
      clearTimeout(this.hideTimeout);
      this.hideTimeout = null;
    }
  }
  hide() {
    if (this.cardEl) {
      this.cardEl.remove();
      this.cardEl = null;
    }
  }
  destroy() {
    this.cancelHide();
    this.hide();
  }
};

// src/people-view.ts
var import_obsidian4 = require("obsidian");
var PeopleView = class extends import_obsidian4.ItemView {
  constructor(leaf, personManager, mentionScanner, profileCard) {
    super(leaf);
    this.searchQuery = "";
    this.sortMode = "alpha";
    this.listEl = null;
    this.personManager = personManager;
    this.mentionScanner = mentionScanner;
    this.profileCard = profileCard;
  }
  getViewType() {
    return VIEW_TYPE_PEOPLE;
  }
  getDisplayText() {
    return "People";
  }
  getIcon() {
    return "users";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("arcadia-connect-people-view");
    const header = container.createDiv({ cls: "arcadia-connect-people-header" });
    const searchContainer = header.createDiv({ cls: "arcadia-connect-search-container" });
    const searchInput = searchContainer.createEl("input", {
      cls: "arcadia-connect-search-input",
      attr: { type: "text", placeholder: "Search people..." }
    });
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value;
      this.renderList();
    });
    const controls = header.createDiv({ cls: "arcadia-connect-controls" });
    const sortSelect = controls.createEl("select", { cls: "arcadia-connect-sort-select" });
    const sortOptions = [
      { value: "alpha", label: "A-Z" },
      { value: "recent", label: "Recent" },
      { value: "relationship", label: "Relationship" }
    ];
    for (const opt of sortOptions) {
      sortSelect.createEl("option", { value: opt.value, text: opt.label });
    }
    sortSelect.value = this.sortMode;
    sortSelect.addEventListener("change", () => {
      this.sortMode = sortSelect.value;
      this.renderList();
    });
    const newBtn = controls.createEl("button", {
      cls: "arcadia-connect-new-btn",
      text: "+ New Person"
    });
    newBtn.addEventListener("click", () => {
      this.createNewPerson();
    });
    this.listEl = container.createDiv({ cls: "arcadia-connect-people-list" });
    this.renderList();
  }
  renderList() {
    if (!this.listEl)
      return;
    this.listEl.empty();
    let people = this.searchQuery ? this.personManager.searchPeople(this.searchQuery) : this.personManager.getAllPeople();
    people = this.sortPeople(people);
    if (people.length === 0) {
      const empty = this.listEl.createDiv({ cls: "arcadia-connect-empty" });
      empty.textContent = this.searchQuery ? "No people match your search." : "No people notes found. Create one to get started.";
      return;
    }
    for (const person of people) {
      const item = this.listEl.createDiv({ cls: "arcadia-connect-person-item" });
      const icon = item.createSpan({ cls: "arcadia-connect-person-icon" });
      icon.textContent = "\u{1F464}";
      const info = item.createDiv({ cls: "arcadia-connect-person-info" });
      info.createDiv({ cls: "arcadia-connect-person-name", text: person.name });
      const meta = [];
      if (person.organization)
        meta.push(person.organization);
      if (person.relationshipType)
        meta.push(person.relationshipType);
      if (meta.length > 0) {
        info.createDiv({
          cls: "arcadia-connect-person-meta",
          text: meta.join(" \xB7 ")
        });
      }
      const mentionCount = this.mentionScanner.getMentionCount(person.name);
      if (mentionCount > 0) {
        const badge = item.createSpan({ cls: "arcadia-connect-mention-badge" });
        badge.textContent = String(mentionCount);
        badge.setAttribute("title", `${mentionCount} mention${mentionCount === 1 ? "" : "s"}`);
      }
      item.addEventListener("click", () => {
        this.app.workspace.openLinkText(person.file.path, "", false);
      });
      item.addEventListener("mouseenter", () => {
        this.profileCard.show(person, item);
      });
      item.addEventListener("mouseleave", () => {
        this.profileCard.scheduleHide();
      });
    }
  }
  sortPeople(people) {
    switch (this.sortMode) {
      case "alpha":
        return [...people].sort((a, b) => a.name.localeCompare(b.name));
      case "recent":
        return [...people].sort((a, b) => {
          const dateA = this.mentionScanner.getLastMentionDate(a.name) || "0000";
          const dateB = this.mentionScanner.getLastMentionDate(b.name) || "0000";
          return dateB.localeCompare(dateA);
        });
      case "relationship":
        return [...people].sort((a, b) => {
          const typeA = a.relationshipType || "zzz";
          const typeB = b.relationshipType || "zzz";
          const cmp = typeA.localeCompare(typeB);
          return cmp !== 0 ? cmp : a.name.localeCompare(b.name);
        });
      default:
        return people;
    }
  }
  async createNewPerson() {
    const name = await this.promptForName();
    if (!name)
      return;
    const file = await this.personManager.createPersonNote(name);
    this.app.workspace.openLinkText(file.path, "", false);
    this.renderList();
  }
  promptForName() {
    return new Promise((resolve) => {
      const modal = document.createElement("div");
      modal.className = "arcadia-connect-name-modal";
      const overlay = document.createElement("div");
      overlay.className = "arcadia-connect-modal-overlay";
      const content = document.createElement("div");
      content.className = "arcadia-connect-modal-content";
      const label = document.createElement("label");
      label.textContent = "Person name:";
      content.appendChild(label);
      const input = document.createElement("input");
      input.type = "text";
      input.className = "arcadia-connect-modal-input";
      input.placeholder = "Full Name";
      content.appendChild(input);
      const buttons = document.createElement("div");
      buttons.className = "arcadia-connect-modal-buttons";
      const cancelBtn = document.createElement("button");
      cancelBtn.textContent = "Cancel";
      cancelBtn.addEventListener("click", () => {
        modal.remove();
        resolve(null);
      });
      buttons.appendChild(cancelBtn);
      const createBtn = document.createElement("button");
      createBtn.textContent = "Create";
      createBtn.className = "mod-cta";
      createBtn.addEventListener("click", () => {
        const value = input.value.trim();
        modal.remove();
        resolve(value || null);
      });
      buttons.appendChild(createBtn);
      content.appendChild(buttons);
      modal.appendChild(overlay);
      modal.appendChild(content);
      document.body.appendChild(modal);
      overlay.addEventListener("click", () => {
        modal.remove();
        resolve(null);
      });
      input.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          const value = input.value.trim();
          modal.remove();
          resolve(value || null);
        }
        if (e.key === "Escape") {
          modal.remove();
          resolve(null);
        }
      });
      input.focus();
    });
  }
  async onClose() {
    this.profileCard.hide();
  }
};

// src/mention-extension.ts
var import_autocomplete = require("@codemirror/autocomplete");
function createMentionExtension(personManager, settings) {
  return (0, import_autocomplete.autocompletion)({
    override: [
      (context) => {
        return mentionCompletionSource(context, personManager, settings);
      }
    ],
    defaultKeymap: true
  });
}
function mentionCompletionSource(context, personManager, settings) {
  const trigger = settings.triggerChar || "@";
  const line = context.state.doc.lineAt(context.pos);
  const lineText = line.text;
  const cursorInLine = context.pos - line.from;
  let triggerPos = -1;
  for (let i = cursorInLine - 1; i >= 0; i--) {
    if (lineText[i] === trigger) {
      if (i === 0 || /[\s\(\[\{,;:!?]/.test(lineText[i - 1])) {
        triggerPos = i;
      }
      break;
    }
    if (/\s/.test(lineText[i])) {
      break;
    }
  }
  if (triggerPos === -1) {
    return null;
  }
  const query = lineText.slice(triggerPos + 1, cursorInLine);
  const from = line.from + triggerPos;
  if (triggerPos > 0 && /[a-zA-Z0-9._-]/.test(lineText[triggerPos - 1])) {
    return null;
  }
  const people = query ? personManager.fuzzyMatch(query) : personManager.getAllPeople();
  if (people.length === 0 && !settings.autoCreatePerson) {
    return null;
  }
  const options = people.map((person) => ({
    label: `${trigger}${person.name}`,
    detail: person.organization || person.relationshipType || "",
    info: person.role || void 0,
    type: "text",
    apply: (view, completion, from2, to) => {
      const peoplePath = settings.peopleFolder.replace(/\/$/, "");
      const wikilink = `[[${peoplePath}/${person.name}|${trigger}${person.name}]]`;
      view.dispatch({
        changes: { from: from2, to, insert: wikilink },
        annotations: import_autocomplete.pickedCompletion.of(completion)
      });
    }
  }));
  if (settings.autoCreatePerson && query && query.length > 0) {
    const exists = people.some((p) => p.name.toLowerCase() === query.toLowerCase());
    if (!exists) {
      options.push({
        label: `${trigger}${query} (new)`,
        detail: "Create new person note",
        type: "text",
        boost: -1,
        apply: (view, completion, from2, to) => {
          const peoplePath = settings.peopleFolder.replace(/\/$/, "");
          const name = query.charAt(0).toUpperCase() + query.slice(1);
          const wikilink = `[[${peoplePath}/${name}|${trigger}${name}]]`;
          view.dispatch({
            changes: { from: from2, to, insert: wikilink },
            annotations: import_autocomplete.pickedCompletion.of(completion)
          });
          personManager.createPersonNote(name);
        }
      });
    }
  }
  return {
    from,
    options,
    filter: false
  };
}

// src/main.ts
var ArcadiaConnectPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.personManager = new PersonManager(this.app, this.settings.peopleFolder);
    this.mentionScanner = new MentionScanner(this.app, this.settings.peopleFolder);
    this.profileCard = new ProfileCard(this.app);
    this.mentionPostProcessor = new MentionPostProcessor(
      this.app,
      this.personManager,
      this.settings,
      this.profileCard
    );
    this.addSettingTab(new ArcadiaConnectSettingTab(this.app, this));
    this.registerView(VIEW_TYPE_PEOPLE, (leaf) => {
      return new PeopleView(
        leaf,
        this.personManager,
        this.mentionScanner,
        this.profileCard
      );
    });
    this.registerEditorExtension(
      createMentionExtension(this.personManager, this.settings)
    );
    this.registerMarkdownPostProcessor(
      this.mentionPostProcessor.getProcessor()
    );
    this.addRibbonIcon("users", "Open People Panel", () => {
      this.activatePeopleView();
    });
    this.addCommand({
      id: "open-people-panel",
      name: "Open People Panel",
      callback: () => {
        this.activatePeopleView();
      }
    });
    this.addCommand({
      id: "create-person-note",
      name: "Create Person Note",
      callback: async () => {
        await this.createPersonNoteCommand();
      }
    });
    this.addCommand({
      id: "mention-person",
      name: "Mention Person",
      editorCallback: (editor) => {
        editor.replaceSelection(this.settings.triggerChar || "@");
      }
    });
    this.app.workspace.onLayoutReady(async () => {
      await this.personManager.initialize();
      await this.mentionScanner.buildIndex();
    });
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (this.personManager.isInPeopleFolder(file)) {
          this.personManager.updatePerson(file);
        }
        this.mentionScanner.onFileChange(file);
        this.refreshPeopleView();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian5.TFile) {
          if (this.personManager.isInPeopleFolder(file)) {
            this.personManager.removePerson(file);
          }
          this.mentionScanner.onFileDelete(file);
          this.refreshPeopleView();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian5.TFile && this.personManager.isInPeopleFolder(file)) {
          setTimeout(() => {
            this.personManager.updatePerson(file);
            this.refreshPeopleView();
          }, 500);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian5.TFile) {
          setTimeout(() => {
            this.personManager.scanPeopleFolder();
            this.mentionScanner.buildIndex();
            this.refreshPeopleView();
          }, 500);
        }
      })
    );
  }
  async onunload() {
    this.profileCard.destroy();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.personManager.setPeopleFolder(this.settings.peopleFolder);
    this.mentionScanner.setPeopleFolder(this.settings.peopleFolder);
    await this.personManager.scanPeopleFolder();
    await this.mentionScanner.buildIndex();
    this.refreshPeopleView();
  }
  async activatePeopleView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_PEOPLE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_PEOPLE,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  refreshPeopleView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_PEOPLE);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof PeopleView) {
        view.renderList();
      }
    }
  }
  async createPersonNoteCommand() {
    const name = await this.promptForName();
    if (!name)
      return;
    const file = await this.personManager.createPersonNote(name);
    await this.app.workspace.openLinkText(file.path, "", false);
  }
  promptForName() {
    return new Promise((resolve) => {
      const modal = document.createElement("div");
      modal.className = "arcadia-connect-name-modal";
      const overlay = document.createElement("div");
      overlay.className = "arcadia-connect-modal-overlay";
      const content = document.createElement("div");
      content.className = "arcadia-connect-modal-content";
      const label = document.createElement("label");
      label.textContent = "Person name:";
      content.appendChild(label);
      const input = document.createElement("input");
      input.type = "text";
      input.className = "arcadia-connect-modal-input";
      input.placeholder = "Full Name";
      content.appendChild(input);
      const buttons = document.createElement("div");
      buttons.className = "arcadia-connect-modal-buttons";
      const cancelBtn = document.createElement("button");
      cancelBtn.textContent = "Cancel";
      cancelBtn.addEventListener("click", () => {
        modal.remove();
        resolve(null);
      });
      buttons.appendChild(cancelBtn);
      const createBtn = document.createElement("button");
      createBtn.textContent = "Create";
      createBtn.className = "mod-cta";
      createBtn.addEventListener("click", () => {
        const value = input.value.trim();
        modal.remove();
        resolve(value || null);
      });
      buttons.appendChild(createBtn);
      content.appendChild(buttons);
      modal.appendChild(overlay);
      modal.appendChild(content);
      document.body.appendChild(modal);
      overlay.addEventListener("click", () => {
        modal.remove();
        resolve(null);
      });
      input.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          const value = input.value.trim();
          modal.remove();
          resolve(value || null);
        }
        if (e.key === "Escape") {
          modal.remove();
          resolve(null);
        }
      });
      input.focus();
    });
  }
};
