/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArcadiaConnectPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian11 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  peopleFolder: "People/",
  triggerChar: "@",
  showHoverCard: true,
  autoCreatePerson: true,
  licenseKey: "",
  licenseStatus: null,
  isPro: false,
  aiProvider: "anthropic",
  anthropicApiKey: "",
  openaiApiKey: "",
  openaiModel: "gpt-4o-mini"
};
var VIEW_TYPE_PEOPLE = "arcadia-connect-people";
var VIEW_TYPE_TIMELINE = "arcadia-connect-timeline";
var VIEW_TYPE_PIPELINE = "arcadia-connect-pipeline";
var PERSON_NOTE_TEMPLATE = `---
file-role: crm-contact
type: person
name: "{{name}}"
email: ""
phone: ""
organization: ""
role: ""
birthday: ""
relationship-type: ""
last-contact: ""
next-follow-up: ""
follow-up-status: pending
deal-stage: ""
deal-value: 0
tags:
  - type/crm-contact
---

# {{name}}

## About

## Interaction Log

`;
var INTERACTION_TYPES = {
  call: "\u{1F4DE} Call",
  email: "\u{1F4E7} Email",
  meeting: "\u{1F91D} Meeting",
  note: "\u{1F4DD} Note",
  other: "\u{1F4AC} Other"
};
var DEAL_STAGE_LABELS = {
  lead: "Lead",
  prospect: "Prospect",
  proposal: "Proposal",
  negotiation: "Negotiation",
  "closed-won": "Closed Won",
  "closed-lost": "Closed Lost",
  nurture: "Nurture"
};
var DEAL_STAGE_ORDER = [
  "lead",
  "prospect",
  "proposal",
  "negotiation",
  "closed-won",
  "closed-lost",
  "nurture"
];

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/license.ts
var import_obsidian = require("obsidian");
var LICENSE_CACHE_DURATION = 24 * 60 * 60 * 1e3;
async function validateLicense(licenseKey, instanceName = "obsidian") {
  var _a, _b, _c;
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://api.lemonsqueezy.com/v1/licenses/validate",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json"
      },
      body: JSON.stringify({ license_key: licenseKey, instance_name: instanceName })
    });
    const data = response.json;
    if (data.valid) {
      return {
        valid: true,
        instanceId: (_a = data.instance) == null ? void 0 : _a.id,
        customerEmail: (_b = data.meta) == null ? void 0 : _b.customer_email,
        expiresAt: (_c = data.license_key) == null ? void 0 : _c.expires_at,
        lastChecked: Date.now()
      };
    }
    return { valid: false, lastChecked: Date.now() };
  } catch (e) {
    return { valid: false, lastChecked: Date.now() };
  }
}

// src/settings.ts
var ArcadiaConnectSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Arcadia Connect settings").setHeading();
    new import_obsidian2.Setting(containerEl).setName("People folder").setDesc("Folder where person notes are stored (relative to vault root).").addText((text) => text.setPlaceholder("People/").setValue(this.plugin.settings.peopleFolder).onChange(async (value) => {
      this.plugin.settings.peopleFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Trigger character").setDesc("Character that triggers the @-mention autocomplete.").addText((text) => text.setPlaceholder("@").setValue(this.plugin.settings.triggerChar).onChange(async (value) => {
      this.plugin.settings.triggerChar = value || "@";
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Show hover card").setDesc("Show a mini profile card when hovering over @-mentions.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showHoverCard).onChange(async (value) => {
      this.plugin.settings.showHoverCard = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Auto-create person note").setDesc("Automatically create a person note when mentioning someone new.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoCreatePerson).onChange(async (value) => {
      this.plugin.settings.autoCreatePerson = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("License").setHeading();
    const licenseStatus = this.plugin.settings.licenseStatus;
    const isPro = this.plugin.settings.isPro && (licenseStatus == null ? void 0 : licenseStatus.valid);
    const statusDesc = isPro ? `Active${(licenseStatus == null ? void 0 : licenseStatus.customerEmail) ? ` (${licenseStatus.customerEmail})` : ""}${(licenseStatus == null ? void 0 : licenseStatus.expiresAt) ? ` - expires ${licenseStatus.expiresAt}` : ""}` : "No active license. Enter your license key and click Validate.";
    const licenseStatusEl = containerEl.createEl("p", {
      text: `License status: ${statusDesc}`,
      cls: isPro ? "mod-success" : "mod-warning"
    });
    let keyInputEl;
    new import_obsidian2.Setting(containerEl).setName("License key").setDesc("Enter your Arcadia Connect Premium license key from Lemon Squeezy.").addText((text) => {
      keyInputEl = text.inputEl;
      text.setPlaceholder("XXXX-XXXX-XXXX-XXXX").setValue(this.plugin.settings.licenseKey).onChange(async (value) => {
        this.plugin.settings.licenseKey = value.trim();
        await this.plugin.saveSettings();
      });
    }).addButton(
      (btn) => btn.setButtonText("Validate").setCta().onClick(async () => {
        const key = this.plugin.settings.licenseKey.trim();
        if (!key)
          return;
        btn.setButtonText("Checking...").setDisabled(true);
        const status = await validateLicense(key);
        this.plugin.settings.licenseStatus = status;
        this.plugin.settings.isPro = status.valid;
        await this.plugin.saveSettings();
        btn.setButtonText("Validate").setDisabled(false);
        if (status.valid) {
          licenseStatusEl.textContent = `License status: Active${status.customerEmail ? ` (${status.customerEmail})` : ""}`;
          licenseStatusEl.className = "mod-success";
        } else {
          licenseStatusEl.textContent = "License status: Invalid or expired. Check your key and try again.";
          licenseStatusEl.className = "mod-warning";
        }
      })
    );
    new import_obsidian2.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("Get Arcadia Connect Premium").onClick(() => {
        window.open("https://arcadia-studio.lemonsqueezy.com", "_blank");
      })
    );
    new import_obsidian2.Setting(containerEl).setName("AI enrichment (BYOK)").setHeading();
    containerEl.createEl("p", {
      text: "Bring your own API key to unlock AI-powered follow-up suggestions. Keys are stored locally in your vault settings and never sent to Arcadia servers.",
      cls: "setting-item-description"
    });
    new import_obsidian2.Setting(containerEl).setName("AI provider").addDropdown(
      (dd) => dd.addOption("anthropic", "Anthropic (Claude)").addOption("openai", "OpenAI").setValue(this.plugin.settings.aiProvider).onChange(async (value) => {
        this.plugin.settings.aiProvider = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.aiProvider === "anthropic") {
      new import_obsidian2.Setting(containerEl).setName("Anthropic API key").setDesc("Your key from console.anthropic.com").addText(
        (text) => text.setPlaceholder("sk-ant-...").setValue(this.plugin.settings.anthropicApiKey).onChange(async (value) => {
          this.plugin.settings.anthropicApiKey = value.trim();
          await this.plugin.saveSettings();
        })
      );
    } else {
      new import_obsidian2.Setting(containerEl).setName("OpenAI API key").setDesc("Your key from platform.openai.com").addText(
        (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
          this.plugin.settings.openaiApiKey = value.trim();
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian2.Setting(containerEl).setName("OpenAI model").addDropdown(
        (dd) => dd.addOption("gpt-4o-mini", "GPT-4o mini (fast, cheap)").addOption("gpt-4o", "GPT-4o (best quality)").addOption("gpt-4-turbo", "GPT-4 Turbo").setValue(this.plugin.settings.openaiModel).onChange(async (value) => {
          this.plugin.settings.openaiModel = value;
          await this.plugin.saveSettings();
        })
      );
    }
  }
};

// src/person-manager.ts
var import_obsidian3 = require("obsidian");
var PersonManager = class {
  constructor(app, peopleFolder) {
    this.people = /* @__PURE__ */ new Map();
    this.app = app;
    this.peopleFolder = peopleFolder;
  }
  setPeopleFolder(folder) {
    this.peopleFolder = folder;
  }
  initialize() {
    this.scanPeopleFolder();
  }
  scanPeopleFolder() {
    this.people.clear();
    const folderPath = (0, import_obsidian3.normalizePath)(this.peopleFolder);
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder || !(folder instanceof import_obsidian3.TFolder)) {
      return;
    }
    const files = folder.children.filter(
      (f) => f instanceof import_obsidian3.TFile && f.extension === "md"
    );
    for (const file of files) {
      const person = this.parsePersonFile(file);
      if (person) {
        this.people.set(person.name.toLowerCase(), person);
      }
    }
  }
  parsePersonFile(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!(cache == null ? void 0 : cache.frontmatter)) {
      return null;
    }
    const fm = cache.frontmatter;
    if (fm.type !== "person" && fm["file-role"] !== "crm-contact") {
      return null;
    }
    const name = fm.name || file.basename;
    if (!name) {
      return null;
    }
    return {
      file,
      name: String(name),
      email: fm.email ? String(fm.email) : void 0,
      phone: fm.phone ? String(fm.phone) : void 0,
      organization: fm.organization ? String(fm.organization) : void 0,
      role: fm.role ? String(fm.role) : void 0,
      birthday: fm.birthday ? String(fm.birthday) : void 0,
      relationshipType: fm["relationship-type"] ? String(fm["relationship-type"]) : void 0,
      tags: Array.isArray(fm.tags) ? fm.tags.map(String) : void 0,
      photo: fm.photo ? String(fm.photo) : void 0,
      // CRM fields
      lastContact: fm["last-contact"] ? String(fm["last-contact"]) : void 0,
      nextFollowUp: fm["next-follow-up"] ? String(fm["next-follow-up"]) : void 0,
      followUpStatus: (_a = fm["follow-up-status"]) != null ? _a : "pending",
      dealStage: fm["deal-stage"] ? fm["deal-stage"] : void 0,
      dealValue: fm["deal-value"] ? Number(fm["deal-value"]) : void 0
    };
  }
  getAllPeople() {
    return Array.from(this.people.values());
  }
  getPersonByName(name) {
    return this.people.get(name.toLowerCase());
  }
  searchPeople(query) {
    if (!query) {
      return this.getAllPeople();
    }
    const lower = query.toLowerCase();
    return this.getAllPeople().filter((p) => {
      return p.name.toLowerCase().includes(lower) || p.organization && p.organization.toLowerCase().includes(lower) || p.tags && p.tags.some((t) => t.toLowerCase().includes(lower)) || p.dealStage && p.dealStage.toLowerCase().includes(lower);
    });
  }
  fuzzyMatch(query) {
    if (!query) {
      return this.getAllPeople();
    }
    const lower = query.toLowerCase();
    return this.getAllPeople().map((p) => ({
      person: p,
      score: this.fuzzyScore(p.name.toLowerCase(), lower)
    })).filter((r) => r.score > 0).sort((a, b) => b.score - a.score).map((r) => r.person);
  }
  fuzzyScore(target, query) {
    let score = 0;
    let qi = 0;
    let consecutive = 0;
    for (let ti = 0; ti < target.length && qi < query.length; ti++) {
      if (target[ti] === query[qi]) {
        score += 1 + consecutive;
        consecutive++;
        qi++;
      } else {
        consecutive = 0;
      }
    }
    if (qi < query.length) {
      return 0;
    }
    if (target.startsWith(query)) {
      score += 10;
    }
    return score;
  }
  getOverdueFollowUps(now = new Date()) {
    const today = now.toISOString().split("T")[0];
    return this.getAllPeople().filter((p) => {
      if (!p.nextFollowUp)
        return false;
      if (p.followUpStatus === "done")
        return false;
      return p.nextFollowUp < today;
    });
  }
  getDueToday(now = new Date()) {
    const today = now.toISOString().split("T")[0];
    return this.getAllPeople().filter((p) => {
      if (!p.nextFollowUp)
        return false;
      if (p.followUpStatus === "done")
        return false;
      return p.nextFollowUp === today;
    });
  }
  async updateFollowUpStatus(file, status) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm["follow-up-status"] = status;
    });
  }
  async logInteraction(person, type, summary, date) {
    await this.app.fileManager.processFrontMatter(person.file, (fm) => {
      fm["last-contact"] = date;
      if (fm["follow-up-status"] === "pending" && fm["next-follow-up"] && fm["next-follow-up"] <= date) {
        fm["follow-up-status"] = "done";
      }
    });
    const content = await this.app.vault.read(person.file);
    const interactionLine = `- ${date} \u2014 **${type}**: ${summary}`;
    let updatedContent;
    const logHeader = "## Interaction Log";
    if (content.includes(logHeader)) {
      updatedContent = content.replace(
        logHeader + "\n",
        logHeader + "\n" + interactionLine + "\n"
      );
    } else {
      updatedContent = content + "\n" + logHeader + "\n" + interactionLine + "\n";
    }
    await this.app.vault.modify(person.file, updatedContent);
    this.updatePerson(person.file);
  }
  async createPersonNote(name) {
    const folderPath = (0, import_obsidian3.normalizePath)(this.peopleFolder);
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
    const content = PERSON_NOTE_TEMPLATE.replace(/\{\{name\}\}/g, name);
    const filePath = (0, import_obsidian3.normalizePath)(`${this.peopleFolder}/${name}.md`);
    const file = await this.app.vault.create(filePath, content);
    const person = {
      file,
      name,
      followUpStatus: "pending"
    };
    this.people.set(name.toLowerCase(), person);
    return file;
  }
  updatePerson(file) {
    const person = this.parsePersonFile(file);
    if (person) {
      this.people.set(person.name.toLowerCase(), person);
    }
  }
  removePerson(file) {
    for (const [key, person] of this.people.entries()) {
      if (person.file.path === file.path) {
        this.people.delete(key);
        break;
      }
    }
  }
  isInPeopleFolder(file) {
    const folderPath = (0, import_obsidian3.normalizePath)(this.peopleFolder);
    return file.path.startsWith(folderPath);
  }
};

// src/mention-scanner.ts
var import_obsidian4 = require("obsidian");
var MentionScanner = class {
  constructor(app, peopleFolder) {
    this.mentionIndex = /* @__PURE__ */ new Map();
    this.app = app;
    this.peopleFolder = peopleFolder;
  }
  setPeopleFolder(folder) {
    this.peopleFolder = folder;
  }
  async buildIndex() {
    this.mentionIndex.clear();
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      if (this.isInPeopleFolder(file))
        continue;
      this.scanFile(file);
    }
  }
  scanFile(file) {
    this.removeFileFromIndex(file);
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache)
      return;
    const peoplePath = (0, import_obsidian4.normalizePath)(this.peopleFolder);
    if (cache.links) {
      for (const link of cache.links) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(
          link.link,
          file.path
        );
        if (resolved && resolved.path.startsWith(peoplePath)) {
          this.addMention(resolved.basename, file, link.position.start.line);
        }
      }
    }
    if (cache.embeds) {
      for (const embed of cache.embeds) {
        const resolved = this.app.metadataCache.getFirstLinkpathDest(
          embed.link,
          file.path
        );
        if (resolved && resolved.path.startsWith(peoplePath)) {
          this.addMention(resolved.basename, file, embed.position.start.line);
        }
      }
    }
  }
  addMention(personName, noteFile, line) {
    const key = personName.toLowerCase();
    if (!this.mentionIndex.has(key)) {
      this.mentionIndex.set(key, []);
    }
    const fileDate = this.extractDateFromFile(noteFile);
    this.mentionIndex.get(key).push({
      personName,
      noteFile,
      noteName: noteFile.basename,
      line,
      date: fileDate
    });
  }
  extractDateFromFile(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.date) {
      return String(cache.frontmatter.date);
    }
    const dateMatch = file.basename.match(/(\d{4}-\d{2}-\d{2})/);
    if (dateMatch) {
      return dateMatch[1];
    }
    return new Date(file.stat.mtime).toISOString().slice(0, 10);
  }
  removeFileFromIndex(file) {
    for (const [key, mentions] of this.mentionIndex.entries()) {
      const filtered = mentions.filter((m) => m.noteFile.path !== file.path);
      if (filtered.length === 0) {
        this.mentionIndex.delete(key);
      } else {
        this.mentionIndex.set(key, filtered);
      }
    }
  }
  getMentionsForPerson(personName) {
    const key = personName.toLowerCase();
    return this.mentionIndex.get(key) || [];
  }
  getRecentMentions(personName, limit = 10) {
    const mentions = this.getMentionsForPerson(personName);
    return mentions.sort((a, b) => b.date.localeCompare(a.date)).slice(0, limit);
  }
  getMentionCount(personName) {
    return this.getMentionsForPerson(personName).length;
  }
  getLastMentionDate(personName) {
    const mentions = this.getMentionsForPerson(personName);
    if (mentions.length === 0)
      return null;
    return mentions.map((m) => m.date).sort().reverse()[0];
  }
  isInPeopleFolder(file) {
    const folderPath = (0, import_obsidian4.normalizePath)(this.peopleFolder);
    return file.path.startsWith(folderPath);
  }
  onFileChange(file) {
    if (!this.isInPeopleFolder(file)) {
      this.scanFile(file);
    }
  }
  onFileDelete(file) {
    this.removeFileFromIndex(file);
  }
};

// src/mention-postprocessor.ts
var MentionPostProcessor = class {
  constructor(app, personManager, settings, profileCard) {
    this.app = app;
    this.personManager = personManager;
    this.settings = settings;
    this.profileCard = profileCard;
  }
  getProcessor() {
    return (el, ctx) => {
      this.processElement(el);
    };
  }
  processElement(el) {
    const trigger = this.settings.triggerChar || "@";
    const walker = document.createTreeWalker(
      el,
      NodeFilter.SHOW_TEXT,
      {
        acceptNode: (node2) => {
          const parent = node2.parentElement;
          if (!parent)
            return NodeFilter.FILTER_REJECT;
          if (parent.tagName === "A" || parent.closest("a") || parent.classList.contains("arcadia-connect-mention")) {
            return NodeFilter.FILTER_REJECT;
          }
          if (node2.textContent && node2.textContent.includes(trigger)) {
            return NodeFilter.FILTER_ACCEPT;
          }
          return NodeFilter.FILTER_REJECT;
        }
      }
    );
    const textNodes = [];
    let node;
    while (node = walker.nextNode()) {
      textNodes.push(node);
    }
    for (const textNode of textNodes) {
      this.processMentionsInText(textNode, trigger);
    }
  }
  processMentionsInText(textNode, trigger) {
    const text = textNode.textContent;
    if (!text)
      return;
    const escapedTrigger = trigger.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(
      `(?:^|(?<=\\s|[([{,;:!?]))${escapedTrigger}([A-Z][a-zA-Z]*(?:\\s[A-Z][a-zA-Z]*)*)`,
      "g"
    );
    const matches = [];
    let match;
    while ((match = regex.exec(text)) !== null) {
      const name = match[1];
      const person = this.personManager.getPersonByName(name);
      if (person) {
        matches.push({
          index: match.index,
          fullMatch: match[0],
          name
        });
      }
    }
    if (matches.length === 0)
      return;
    const parent = textNode.parentNode;
    if (!parent)
      return;
    const fragment = document.createDocumentFragment();
    let lastIndex = 0;
    for (const m of matches) {
      if (m.index > lastIndex) {
        fragment.appendChild(
          document.createTextNode(text.slice(lastIndex, m.index))
        );
      }
      const span = document.createElement("span");
      span.className = "arcadia-connect-mention";
      span.textContent = m.fullMatch;
      span.setAttribute("data-person-name", m.name);
      span.addEventListener("click", (e) => {
        e.preventDefault();
        const person = this.personManager.getPersonByName(m.name);
        if (person) {
          this.app.workspace.openLinkText(person.file.path, "", false);
        }
      });
      if (this.settings.showHoverCard) {
        span.addEventListener("mouseenter", (e) => {
          const person = this.personManager.getPersonByName(m.name);
          if (person) {
            this.profileCard.show(person, span);
          }
        });
        span.addEventListener("mouseleave", () => {
          this.profileCard.scheduleHide();
        });
      }
      fragment.appendChild(span);
      lastIndex = m.index + m.fullMatch.length;
    }
    if (lastIndex < text.length) {
      fragment.appendChild(document.createTextNode(text.slice(lastIndex)));
    }
    parent.replaceChild(fragment, textNode);
  }
};

// src/profile-card.ts
var ProfileCard = class {
  constructor(app) {
    this.cardEl = null;
    this.hideTimeout = null;
    this.app = app;
  }
  show(person, anchor) {
    this.cancelHide();
    this.hide();
    const card = document.createElement("div");
    card.className = "arcadia-connect-profile-card";
    const header = card.createDiv({ cls: "arcadia-connect-card-header" });
    const icon = header.createSpan({ cls: "arcadia-connect-card-icon" });
    icon.textContent = "\u{1F464}";
    header.createEl("strong", { text: person.name });
    const details = card.createDiv({ cls: "arcadia-connect-card-details" });
    if (person.organization) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Org" });
      row.createSpan({ text: person.organization });
    }
    if (person.role) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Role" });
      row.createSpan({ text: person.role });
    }
    if (person.email) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Email" });
      row.createSpan({ text: person.email });
    }
    if (person.phone) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Phone" });
      row.createSpan({ text: person.phone });
    }
    if (person.relationshipType) {
      const row = details.createDiv({ cls: "arcadia-connect-card-row" });
      row.createSpan({ cls: "arcadia-connect-card-label", text: "Type" });
      row.createSpan({ text: person.relationshipType });
    }
    const footer = card.createDiv({ cls: "arcadia-connect-card-footer" });
    const openBtn = footer.createEl("button", {
      cls: "arcadia-connect-card-open-btn",
      text: "Open"
    });
    openBtn.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      void this.app.workspace.openLinkText(person.file.path, "", false);
      this.hide();
    });
    document.body.appendChild(card);
    this.cardEl = card;
    const anchorRect = anchor.getBoundingClientRect();
    const cardRect = card.getBoundingClientRect();
    let top = anchorRect.bottom + 4;
    let left = anchorRect.left;
    if (top + cardRect.height > window.innerHeight) {
      top = anchorRect.top - cardRect.height - 4;
    }
    if (left + cardRect.width > window.innerWidth) {
      left = window.innerWidth - cardRect.width - 8;
    }
    if (left < 0)
      left = 8;
    card.style.top = `${top}px`;
    card.style.left = `${left}px`;
    card.addEventListener("mouseenter", () => {
      this.cancelHide();
    });
    card.addEventListener("mouseleave", () => {
      this.scheduleHide();
    });
  }
  scheduleHide() {
    this.cancelHide();
    this.hideTimeout = setTimeout(() => {
      this.hide();
    }, 300);
  }
  cancelHide() {
    if (this.hideTimeout) {
      clearTimeout(this.hideTimeout);
      this.hideTimeout = null;
    }
  }
  hide() {
    if (this.cardEl) {
      this.cardEl.remove();
      this.cardEl = null;
    }
  }
  destroy() {
    this.cancelHide();
    this.hide();
  }
};

// src/people-view.ts
var import_obsidian6 = require("obsidian");

// src/interaction-logger.ts
var import_obsidian5 = require("obsidian");
var InteractionLoggerModal = class extends import_obsidian5.Modal {
  constructor(app, personManager, preselectedPerson = null, onSuccess) {
    super(app);
    this.personManager = personManager;
    this.preselectedPerson = preselectedPerson;
    this.onSuccess = onSuccess;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("arcadia-interaction-modal");
    contentEl.createEl("h2", { text: "Log Interaction" });
    const today = new Date().toISOString().split("T")[0];
    let selectedPerson = this.preselectedPerson;
    let selectedType = "call";
    let selectedDate = today;
    let summary = "";
    let nextFollowUp = "";
    if (!this.preselectedPerson) {
      const people = this.personManager.getAllPeople();
      new import_obsidian5.Setting(contentEl).setName("Person").setDesc("Who did you interact with?").addDropdown((dd) => {
        dd.addOption("", "\u2014 Select person \u2014");
        for (const p of people.sort((a, b) => a.name.localeCompare(b.name))) {
          dd.addOption(p.name, p.name);
        }
        dd.onChange((value) => {
          var _a;
          selectedPerson = (_a = this.personManager.getPersonByName(value)) != null ? _a : null;
        });
      });
    } else {
      contentEl.createEl("p", {
        text: `Contact: ${this.preselectedPerson.name}`,
        cls: "arcadia-interaction-contact-name"
      });
    }
    new import_obsidian5.Setting(contentEl).setName("Type").addDropdown((dd) => {
      for (const [value, label] of Object.entries(INTERACTION_TYPES)) {
        dd.addOption(value, label);
      }
      dd.setValue("call");
      dd.onChange((value) => {
        selectedType = value;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Date").addText((text) => {
      text.setValue(today);
      text.inputEl.type = "date";
      text.onChange((value) => {
        selectedDate = value;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Summary").setDesc("Brief description of the interaction").addTextArea((ta) => {
      ta.setPlaceholder("What was discussed or decided?");
      ta.inputEl.rows = 3;
      ta.onChange((value) => {
        summary = value;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Next follow-up").setDesc("Optional: schedule a follow-up").addText((text) => {
      text.inputEl.type = "date";
      text.onChange((value) => {
        nextFollowUp = value;
      });
    });
    const buttonRow = contentEl.createDiv({ cls: "arcadia-interaction-buttons" });
    const cancelBtn = buttonRow.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    const saveBtn = buttonRow.createEl("button", {
      text: "Log Interaction",
      cls: "mod-cta"
    });
    saveBtn.addEventListener("click", () => {
      void (async () => {
        var _a;
        if (!selectedPerson) {
          new import_obsidian5.Notice("Please select a person.");
          return;
        }
        if (!summary.trim()) {
          new import_obsidian5.Notice("Please add a summary.");
          return;
        }
        try {
          await this.personManager.logInteraction(
            selectedPerson,
            INTERACTION_TYPES[selectedType],
            summary.trim(),
            selectedDate
          );
          if (nextFollowUp) {
            await this.app.fileManager.processFrontMatter(selectedPerson.file, (fm) => {
              fm["next-follow-up"] = nextFollowUp;
              fm["follow-up-status"] = "pending";
            });
          }
          new import_obsidian5.Notice(`Logged interaction with ${selectedPerson.name}`);
          this.close();
          (_a = this.onSuccess) == null ? void 0 : _a.call(this);
        } catch (e) {
          new import_obsidian5.Notice("Failed to log interaction. Check console for details.");
          console.error("Interaction log error:", e);
        }
      })();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var SetFollowUpModal = class extends import_obsidian5.Modal {
  constructor(app, person, personManager, onSuccess) {
    super(app);
    this.person = person;
    this.personManager = personManager;
    this.onSuccess = onSuccess;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("arcadia-followup-modal");
    contentEl.createEl("h2", { text: `Follow-up: ${this.person.name}` });
    let followUpDate = "";
    let notes = "";
    new import_obsidian5.Setting(contentEl).setName("Follow-up date").addText((text) => {
      text.inputEl.type = "date";
      const nextWeek = new Date();
      nextWeek.setDate(nextWeek.getDate() + 7);
      text.setValue(nextWeek.toISOString().split("T")[0]);
      followUpDate = nextWeek.toISOString().split("T")[0];
      text.onChange((value) => {
        followUpDate = value;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Note").setDesc("What to follow up about (optional)").addText((text) => {
      text.setPlaceholder("Reminder note...");
      text.onChange((value) => {
        notes = value;
      });
    });
    const buttonRow = contentEl.createDiv({ cls: "arcadia-interaction-buttons" });
    const cancelBtn = buttonRow.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    const saveBtn = buttonRow.createEl("button", { text: "Set Follow-up", cls: "mod-cta" });
    saveBtn.addEventListener("click", () => {
      void (async () => {
        var _a;
        if (!followUpDate) {
          new import_obsidian5.Notice("Please select a date.");
          return;
        }
        await this.app.fileManager.processFrontMatter(this.person.file, (fm) => {
          fm["next-follow-up"] = followUpDate;
          fm["follow-up-status"] = "pending";
          if (notes.trim()) {
            fm["follow-up-note"] = notes.trim();
          }
        });
        new import_obsidian5.Notice(`Follow-up set for ${this.person.name} on ${followUpDate}`);
        this.close();
        (_a = this.onSuccess) == null ? void 0 : _a.call(this);
      })();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/people-view.ts
var PeopleView = class extends import_obsidian6.ItemView {
  constructor(leaf, personManager, mentionScanner, profileCard) {
    super(leaf);
    this.searchQuery = "";
    this.sortMode = "alpha";
    this.filterOverdue = false;
    this.listEl = null;
    this.personManager = personManager;
    this.mentionScanner = mentionScanner;
    this.profileCard = profileCard;
  }
  getViewType() {
    return VIEW_TYPE_PEOPLE;
  }
  getDisplayText() {
    return "People";
  }
  getIcon() {
    return "users";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("arcadia-connect-people-view");
    const header = container.createDiv({ cls: "arcadia-connect-people-header" });
    const searchContainer = header.createDiv({ cls: "arcadia-connect-search-container" });
    const searchInput = searchContainer.createEl("input", {
      cls: "arcadia-connect-search-input",
      attr: { type: "text", placeholder: "Search people..." }
    });
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value;
      this.renderList();
    });
    const controls = header.createDiv({ cls: "arcadia-connect-controls" });
    const sortSelect = controls.createEl("select", { cls: "arcadia-connect-sort-select" });
    const sortOptions = [
      { value: "alpha", label: "A-Z" },
      { value: "recent", label: "Recent mention" },
      { value: "last-contact", label: "Last contacted" },
      { value: "next-follow-up", label: "Follow-up due" },
      { value: "deal-stage", label: "Deal stage" },
      { value: "relationship", label: "Relationship" }
    ];
    for (const opt of sortOptions) {
      sortSelect.createEl("option", { value: opt.value, text: opt.label });
    }
    sortSelect.value = this.sortMode;
    sortSelect.addEventListener("change", () => {
      this.sortMode = sortSelect.value;
      this.filterOverdue = false;
      this.renderList();
    });
    const overdueBtn = controls.createEl("button", {
      cls: "arcadia-connect-overdue-btn",
      text: "\u23F0",
      attr: { title: "Show overdue follow-ups" }
    });
    overdueBtn.addEventListener("click", () => {
      this.filterOverdue = !this.filterOverdue;
      overdueBtn.toggleClass("is-active", this.filterOverdue);
      this.renderList();
    });
    const newBtn = controls.createEl("button", {
      cls: "arcadia-connect-new-btn",
      text: "+ Person"
    });
    newBtn.addEventListener("click", () => {
      void this.createNewPerson();
    });
    const logBtn = controls.createEl("button", {
      cls: "arcadia-connect-log-btn",
      text: "+ Log",
      attr: { title: "Log an interaction" }
    });
    logBtn.addEventListener("click", () => {
      new InteractionLoggerModal(this.app, this.personManager, null, () => {
        this.renderList();
      }).open();
    });
    this.listEl = container.createDiv({ cls: "arcadia-connect-people-list" });
    this.renderList();
  }
  renderList() {
    var _a;
    if (!this.listEl)
      return;
    this.listEl.empty();
    let people = this.searchQuery ? this.personManager.searchPeople(this.searchQuery) : this.personManager.getAllPeople();
    if (this.filterOverdue) {
      const today2 = new Date().toISOString().split("T")[0];
      people = people.filter((p) => {
        if (!p.nextFollowUp)
          return false;
        if (p.followUpStatus === "done")
          return false;
        return p.nextFollowUp <= today2;
      });
    }
    people = this.sortPeople(people);
    if (people.length === 0) {
      const empty = this.listEl.createDiv({ cls: "arcadia-connect-empty" });
      if (this.filterOverdue) {
        empty.textContent = "No overdue follow-ups.";
      } else if (this.searchQuery) {
        empty.textContent = "No people match your search.";
      } else {
        empty.textContent = "No people notes found. Create one to get started.";
      }
      return;
    }
    const today = new Date().toISOString().split("T")[0];
    for (const person of people) {
      const item = this.listEl.createDiv({ cls: "arcadia-connect-person-item" });
      const followUpOverdue = person.nextFollowUp && person.followUpStatus !== "done" && person.nextFollowUp < today;
      const followUpDueToday = person.nextFollowUp && person.followUpStatus !== "done" && person.nextFollowUp === today;
      if (followUpOverdue)
        item.addClass("has-overdue-followup");
      if (followUpDueToday)
        item.addClass("has-followup-today");
      const icon = item.createSpan({ cls: "arcadia-connect-person-icon" });
      icon.textContent = followUpOverdue ? "\u23F0" : followUpDueToday ? "\u{1F514}" : "\u{1F464}";
      const info = item.createDiv({ cls: "arcadia-connect-person-info" });
      info.createDiv({ cls: "arcadia-connect-person-name", text: person.name });
      const meta = [];
      if (person.organization)
        meta.push(person.organization);
      if (person.dealStage)
        meta.push((_a = DEAL_STAGE_LABELS[person.dealStage]) != null ? _a : person.dealStage);
      if (meta.length > 0) {
        info.createDiv({
          cls: "arcadia-connect-person-meta",
          text: meta.join(" \xB7 ")
        });
      }
      if (person.lastContact || person.nextFollowUp) {
        const dateLine = info.createDiv({ cls: "arcadia-connect-person-dates" });
        if (person.lastContact) {
          dateLine.createSpan({ cls: "arcadia-date-last", text: `Last: ${person.lastContact}` });
        }
        if (person.nextFollowUp && person.followUpStatus !== "done") {
          const cls = followUpOverdue ? "arcadia-date-followup overdue" : followUpDueToday ? "arcadia-date-followup due-today" : "arcadia-date-followup";
          dateLine.createSpan({ cls, text: ` \xB7 Due: ${person.nextFollowUp}` });
        }
      }
      const mentionCount = this.mentionScanner.getMentionCount(person.name);
      if (mentionCount > 0) {
        const badge = item.createSpan({ cls: "arcadia-connect-mention-badge" });
        badge.textContent = String(mentionCount);
        badge.setAttribute("title", `${mentionCount} mention${mentionCount === 1 ? "" : "s"}`);
      }
      const actions = item.createDiv({ cls: "arcadia-connect-item-actions" });
      const logBtn = actions.createEl("button", {
        cls: "arcadia-connect-action-btn",
        text: "+ Log",
        attr: { title: "Log interaction" }
      });
      logBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        new InteractionLoggerModal(this.app, this.personManager, person, () => {
          this.renderList();
        }).open();
      });
      const followUpBtn = actions.createEl("button", {
        cls: "arcadia-connect-action-btn",
        text: "\u{1F4C5}",
        attr: { title: "Set follow-up" }
      });
      followUpBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        new SetFollowUpModal(this.app, person, this.personManager, () => {
          this.renderList();
        }).open();
      });
      item.addEventListener("click", () => {
        this.app.workspace.openLinkText(person.file.path, "", false);
      });
      item.addEventListener("mouseenter", () => {
        this.profileCard.show(person, item);
      });
      item.addEventListener("mouseleave", () => {
        this.profileCard.scheduleHide();
      });
    }
  }
  sortPeople(people) {
    const FAR_FUTURE = "9999-99-99";
    const FAR_PAST = "0000-00-00";
    switch (this.sortMode) {
      case "alpha":
        return [...people].sort((a, b) => a.name.localeCompare(b.name));
      case "recent":
        return [...people].sort((a, b) => {
          const dateA = this.mentionScanner.getLastMentionDate(a.name) || FAR_PAST;
          const dateB = this.mentionScanner.getLastMentionDate(b.name) || FAR_PAST;
          return dateB.localeCompare(dateA);
        });
      case "last-contact":
        return [...people].sort((a, b) => {
          const dateA = a.lastContact || FAR_PAST;
          const dateB = b.lastContact || FAR_PAST;
          return dateB.localeCompare(dateA);
        });
      case "next-follow-up":
        return [...people].sort((a, b) => {
          const dateA = (a.followUpStatus === "done" ? FAR_FUTURE : a.nextFollowUp) || FAR_FUTURE;
          const dateB = (b.followUpStatus === "done" ? FAR_FUTURE : b.nextFollowUp) || FAR_FUTURE;
          return dateA.localeCompare(dateB);
        });
      case "deal-stage": {
        const stageOrder = ["lead", "prospect", "proposal", "negotiation", "closed-won", "closed-lost", "nurture"];
        return [...people].sort((a, b) => {
          const ia = a.dealStage ? stageOrder.indexOf(a.dealStage) : stageOrder.length;
          const ib = b.dealStage ? stageOrder.indexOf(b.dealStage) : stageOrder.length;
          return ia !== ib ? ia - ib : a.name.localeCompare(b.name);
        });
      }
      case "relationship":
        return [...people].sort((a, b) => {
          const typeA = a.relationshipType || "zzz";
          const typeB = b.relationshipType || "zzz";
          const cmp = typeA.localeCompare(typeB);
          return cmp !== 0 ? cmp : a.name.localeCompare(b.name);
        });
      default:
        return people;
    }
  }
  async createNewPerson() {
    const name = await this.promptForName();
    if (!name)
      return;
    const file = await this.personManager.createPersonNote(name);
    await this.app.workspace.openLinkText(file.path, "", false);
    this.renderList();
  }
  promptForName() {
    return new Promise((resolve) => {
      const modal = document.createElement("div");
      modal.className = "arcadia-connect-name-modal";
      const overlay = document.createElement("div");
      overlay.className = "arcadia-connect-modal-overlay";
      const content = document.createElement("div");
      content.className = "arcadia-connect-modal-content";
      const label = document.createElement("label");
      label.textContent = "Person name:";
      content.appendChild(label);
      const input = document.createElement("input");
      input.type = "text";
      input.className = "arcadia-connect-modal-input";
      input.placeholder = "Full Name";
      content.appendChild(input);
      const buttons = document.createElement("div");
      buttons.className = "arcadia-connect-modal-buttons";
      const cancelBtn = document.createElement("button");
      cancelBtn.textContent = "Cancel";
      cancelBtn.addEventListener("click", () => {
        modal.remove();
        resolve(null);
      });
      buttons.appendChild(cancelBtn);
      const createBtn = document.createElement("button");
      createBtn.textContent = "Create";
      createBtn.className = "mod-cta";
      createBtn.addEventListener("click", () => {
        const value = input.value.trim();
        modal.remove();
        resolve(value || null);
      });
      buttons.appendChild(createBtn);
      content.appendChild(buttons);
      modal.appendChild(overlay);
      modal.appendChild(content);
      document.body.appendChild(modal);
      overlay.addEventListener("click", () => {
        modal.remove();
        resolve(null);
      });
      input.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          const value = input.value.trim();
          modal.remove();
          resolve(value || null);
        }
        if (e.key === "Escape") {
          modal.remove();
          resolve(null);
        }
      });
      input.focus();
    });
  }
  async onClose() {
    this.profileCard.hide();
  }
};

// src/timeline-view.ts
var import_obsidian7 = require("obsidian");
var INTERACTION_RE = /^- (\d{4}-\d{2}-\d{2}) — \*\*(.+?)\*\*: (.+)$/;
var TimelineView = class extends import_obsidian7.ItemView {
  constructor(leaf, personManager) {
    super(leaf);
    this.entries = [];
    this.filterContact = "";
    this.listEl = null;
    this.personManager = personManager;
  }
  getViewType() {
    return VIEW_TYPE_TIMELINE;
  }
  getDisplayText() {
    return "Interaction Timeline";
  }
  getIcon() {
    return "history";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("arcadia-timeline-view");
    const header = container.createDiv({ cls: "arcadia-timeline-header" });
    header.createEl("h4", { text: "Interaction Timeline" });
    const controls = header.createDiv({ cls: "arcadia-timeline-controls" });
    const filterInput = controls.createEl("input", {
      cls: "arcadia-timeline-filter",
      attr: { type: "text", placeholder: "Filter by contact..." }
    });
    filterInput.addEventListener("input", () => {
      this.filterContact = filterInput.value.toLowerCase();
      this.renderEntries();
    });
    const refreshBtn = controls.createEl("button", {
      cls: "arcadia-timeline-refresh",
      text: "\u21BB",
      attr: { title: "Refresh" }
    });
    refreshBtn.addEventListener("click", () => {
      void this.reload();
    });
    this.listEl = container.createDiv({ cls: "arcadia-timeline-list" });
    await this.reload();
  }
  async reload() {
    this.entries = await this.parseAllInteractions();
    this.renderEntries();
  }
  async parseAllInteractions() {
    const entries = [];
    const people = this.personManager.getAllPeople();
    for (const person of people) {
      try {
        const content = await this.app.vault.read(person.file);
        const logStart = content.indexOf("## Interaction Log");
        if (logStart === -1)
          continue;
        const logSection = content.slice(logStart);
        const lines = logSection.split("\n");
        for (const line of lines) {
          const match = line.match(INTERACTION_RE);
          if (!match)
            continue;
          entries.push({
            date: match[1],
            type: match[2],
            summary: match[3].trim(),
            contactName: person.name,
            contactFile: person.file
          });
        }
      } catch (e) {
      }
    }
    return entries.sort((a, b) => b.date.localeCompare(a.date));
  }
  renderEntries() {
    if (!this.listEl)
      return;
    this.listEl.empty();
    let filtered = this.entries;
    if (this.filterContact) {
      filtered = filtered.filter(
        (e) => e.contactName.toLowerCase().includes(this.filterContact)
      );
    }
    if (filtered.length === 0) {
      const empty = this.listEl.createDiv({ cls: "arcadia-timeline-empty" });
      empty.textContent = this.filterContact ? "No interactions found for that contact." : 'No interactions logged yet. Use "Log Interaction" to get started.';
      return;
    }
    const today = new Date().toISOString().split("T")[0];
    const yesterday = new Date(Date.now() - 864e5).toISOString().split("T")[0];
    const weekAgo = new Date(Date.now() - 7 * 864e5).toISOString().split("T")[0];
    const monthAgo = new Date(Date.now() - 30 * 864e5).toISOString().split("T")[0];
    const getBucket = (date) => {
      if (date === today)
        return "Today";
      if (date === yesterday)
        return "Yesterday";
      if (date >= weekAgo)
        return "This Week";
      if (date >= monthAgo)
        return "This Month";
      return "Earlier";
    };
    let currentBucket = "";
    for (const entry of filtered) {
      const bucket = getBucket(entry.date);
      if (bucket !== currentBucket) {
        currentBucket = bucket;
        const bucketHeader = this.listEl.createDiv({ cls: "arcadia-timeline-bucket" });
        bucketHeader.textContent = bucket;
      }
      const row = this.listEl.createDiv({ cls: "arcadia-timeline-entry" });
      const dateBadge = row.createDiv({ cls: "arcadia-timeline-date" });
      dateBadge.textContent = entry.date;
      const body = row.createDiv({ cls: "arcadia-timeline-body" });
      const topLine = body.createDiv({ cls: "arcadia-timeline-top" });
      const typeBadge = topLine.createSpan({ cls: "arcadia-timeline-type" });
      typeBadge.textContent = entry.type;
      const contactLink = topLine.createEl("a", {
        cls: "arcadia-timeline-contact",
        text: entry.contactName
      });
      contactLink.addEventListener("click", (e) => {
        e.preventDefault();
        this.app.workspace.openLinkText(entry.contactFile.path, "", false);
      });
      body.createDiv({
        cls: "arcadia-timeline-summary",
        text: entry.summary
      });
    }
  }
  async onClose() {
  }
};

// src/pipeline-view.ts
var import_obsidian8 = require("obsidian");
var PipelineView = class extends import_obsidian8.ItemView {
  constructor(leaf, personManager) {
    super(leaf);
    this.boardEl = null;
    this.personManager = personManager;
  }
  getViewType() {
    return VIEW_TYPE_PIPELINE;
  }
  getDisplayText() {
    return "Pipeline";
  }
  getIcon() {
    return "kanban-square";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("arcadia-pipeline-view");
    const header = container.createDiv({ cls: "arcadia-pipeline-header" });
    header.createEl("h4", { text: "Deal pipeline" });
    const refreshBtn = header.createEl("button", {
      cls: "arcadia-pipeline-refresh",
      text: "\u21BB",
      attr: { title: "Refresh" }
    });
    refreshBtn.addEventListener("click", () => this.renderBoard());
    this.boardEl = container.createDiv({ cls: "arcadia-pipeline-board" });
    this.renderBoard();
  }
  renderBoard() {
    var _a, _b;
    if (!this.boardEl)
      return;
    this.boardEl.empty();
    const people = this.personManager.getAllPeople();
    const today = new Date().toISOString().split("T")[0];
    const byStage = /* @__PURE__ */ new Map();
    for (const stage of DEAL_STAGE_ORDER) {
      byStage.set(stage, []);
    }
    for (const person of people) {
      const stage = (_a = person.dealStage) != null ? _a : "lead";
      const bucket = byStage.get(stage);
      if (bucket)
        bucket.push(person);
    }
    const visibleStages = ["lead", "prospect", "proposal", "negotiation", "closed-won", "closed-lost"];
    for (const stage of visibleStages) {
      const contacts = (_b = byStage.get(stage)) != null ? _b : [];
      const column = this.boardEl.createDiv({ cls: `arcadia-pipeline-column arcadia-stage-${stage}` });
      const colHeader = column.createDiv({ cls: "arcadia-pipeline-col-header" });
      colHeader.createSpan({ cls: "arcadia-pipeline-stage-name", text: DEAL_STAGE_LABELS[stage] });
      const countBadge = colHeader.createSpan({ cls: "arcadia-pipeline-count" });
      countBadge.textContent = String(contacts.length);
      const stageValue = contacts.reduce((sum, p) => {
        var _a2;
        return sum + ((_a2 = p.dealValue) != null ? _a2 : 0);
      }, 0);
      if (stageValue > 0) {
        colHeader.createSpan({
          cls: "arcadia-pipeline-value",
          text: `$${stageValue.toLocaleString()}`
        });
      }
      const cardsEl = column.createDiv({ cls: "arcadia-pipeline-cards" });
      if (contacts.length === 0) {
        cardsEl.createDiv({ cls: "arcadia-pipeline-empty-col", text: "Empty" });
      }
      for (const person of contacts.sort((a, b) => {
        var _a2, _b2;
        return ((_a2 = b.dealValue) != null ? _a2 : 0) - ((_b2 = a.dealValue) != null ? _b2 : 0);
      })) {
        const card = cardsEl.createDiv({ cls: "arcadia-pipeline-card" });
        const hasOverdue = person.nextFollowUp && person.followUpStatus !== "done" && person.nextFollowUp < today;
        const hasDueToday = person.nextFollowUp && person.followUpStatus !== "done" && person.nextFollowUp === today;
        if (hasOverdue)
          card.addClass("has-overdue");
        if (hasDueToday)
          card.addClass("has-due-today");
        const cardTop = card.createDiv({ cls: "arcadia-card-top" });
        cardTop.createDiv({ cls: "arcadia-card-name", text: person.name });
        if (hasOverdue)
          cardTop.createSpan({ cls: "arcadia-card-flag", text: "\u23F0" });
        else if (hasDueToday)
          cardTop.createSpan({ cls: "arcadia-card-flag", text: "\u{1F514}" });
        if (person.organization) {
          card.createDiv({ cls: "arcadia-card-org", text: person.organization });
        }
        if (person.dealValue && person.dealValue > 0) {
          card.createDiv({
            cls: "arcadia-card-deal-value",
            text: `$${person.dealValue.toLocaleString()}`
          });
        }
        if (person.lastContact) {
          card.createDiv({
            cls: "arcadia-card-last-contact",
            text: `Last: ${person.lastContact}`
          });
        }
        const actions = card.createDiv({ cls: "arcadia-card-actions" });
        const moveSelect = actions.createEl("select", { cls: "arcadia-card-move-select" });
        moveSelect.createEl("option", { value: "", text: "Move to..." });
        for (const s of DEAL_STAGE_ORDER) {
          if (s === stage)
            continue;
          moveSelect.createEl("option", { value: s, text: DEAL_STAGE_LABELS[s] });
        }
        moveSelect.addEventListener("change", async () => {
          const newStage = moveSelect.value;
          if (!newStage)
            return;
          await this.app.fileManager.processFrontMatter(person.file, (fm) => {
            fm["deal-stage"] = newStage;
          });
          this.personManager.updatePerson(person.file);
          new import_obsidian8.Notice(`Moved ${person.name} to ${DEAL_STAGE_LABELS[newStage]}`);
          this.renderBoard();
        });
        const logBtn = actions.createEl("button", {
          cls: "arcadia-card-log-btn",
          text: "+ Log",
          attr: { title: "Log interaction" }
        });
        logBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          new InteractionLoggerModal(this.app, this.personManager, person, () => {
            this.renderBoard();
          }).open();
        });
        card.addEventListener("click", (e) => {
          if (e.target.closest("select, button"))
            return;
          this.app.workspace.openLinkText(person.file.path, "", false);
        });
      }
    }
  }
  async onClose() {
  }
};

// src/mention-extension.ts
var import_autocomplete = require("@codemirror/autocomplete");
function createMentionExtension(personManager, settings) {
  return (0, import_autocomplete.autocompletion)({
    override: [
      (context) => {
        return mentionCompletionSource(context, personManager, settings);
      }
    ],
    defaultKeymap: true
  });
}
function mentionCompletionSource(context, personManager, settings) {
  const trigger = settings.triggerChar || "@";
  const line = context.state.doc.lineAt(context.pos);
  const lineText = line.text;
  const cursorInLine = context.pos - line.from;
  let triggerPos = -1;
  for (let i = cursorInLine - 1; i >= 0; i--) {
    if (lineText[i] === trigger) {
      if (i === 0 || /[\s([{,;:!?]/.test(lineText[i - 1])) {
        triggerPos = i;
      }
      break;
    }
    if (/\s/.test(lineText[i])) {
      break;
    }
  }
  if (triggerPos === -1) {
    return null;
  }
  const query = lineText.slice(triggerPos + 1, cursorInLine);
  const from = line.from + triggerPos;
  if (triggerPos > 0 && /[a-zA-Z0-9._-]/.test(lineText[triggerPos - 1])) {
    return null;
  }
  const people = query ? personManager.fuzzyMatch(query) : personManager.getAllPeople();
  if (people.length === 0 && !settings.autoCreatePerson) {
    return null;
  }
  const options = people.map((person) => ({
    label: `${trigger}${person.name}`,
    detail: person.organization || person.relationshipType || "",
    info: person.role || void 0,
    type: "text",
    apply: (view, completion, from2, to) => {
      const peoplePath = settings.peopleFolder.replace(/\/$/, "");
      const wikilink = `[[${peoplePath}/${person.name}|${trigger}${person.name}]]`;
      view.dispatch({
        changes: { from: from2, to, insert: wikilink },
        annotations: import_autocomplete.pickedCompletion.of(completion)
      });
    }
  }));
  if (settings.autoCreatePerson && query && query.length > 0) {
    const exists = people.some((p) => p.name.toLowerCase() === query.toLowerCase());
    if (!exists) {
      options.push({
        label: `${trigger}${query} (new)`,
        detail: "Create new person note",
        type: "text",
        boost: -1,
        apply: (view, completion, from2, to) => {
          const peoplePath = settings.peopleFolder.replace(/\/$/, "");
          const name = query.charAt(0).toUpperCase() + query.slice(1);
          const wikilink = `[[${peoplePath}/${name}|${trigger}${name}]]`;
          view.dispatch({
            changes: { from: from2, to, insert: wikilink },
            annotations: import_autocomplete.pickedCompletion.of(completion)
          });
          void personManager.createPersonNote(name);
        }
      });
    }
  }
  return {
    from,
    options,
    filter: false
  };
}

// src/followup-engine.ts
var import_obsidian9 = require("obsidian");
var CHECK_INTERVAL_MS = 60 * 60 * 1e3;
var FollowUpEngine = class {
  constructor(personManager) {
    this.intervalId = null;
    this.firedToday = /* @__PURE__ */ new Set();
    this.lastFiredDate = "";
    this.personManager = personManager;
  }
  start() {
    this.check();
    this.intervalId = window.setInterval(() => this.check(), CHECK_INTERVAL_MS);
  }
  stop() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }
  check() {
    const today = new Date().toISOString().split("T")[0];
    if (today !== this.lastFiredDate) {
      this.firedToday.clear();
      this.lastFiredDate = today;
    }
    const overdue = this.personManager.getOverdueFollowUps();
    const dueToday = this.personManager.getDueToday();
    for (const person of dueToday) {
      const key = `today:${person.file.path}`;
      if (!this.firedToday.has(key)) {
        this.firedToday.add(key);
        this.showFollowUpNotice(person, false);
      }
    }
    if (overdue.length > 0) {
      const overdueKey = `overdue:${today}`;
      if (!this.firedToday.has(overdueKey)) {
        this.firedToday.add(overdueKey);
        this.showOverdueSummary(overdue);
      }
    }
  }
  showFollowUpNotice(person, isOverdue) {
    const prefix = isOverdue ? "Overdue" : "Follow-up due today";
    const msg = `${prefix}: ${person.name}`;
    if (person.organization) {
      new import_obsidian9.Notice(`${msg} (${person.organization})`, 8e3);
    } else {
      new import_obsidian9.Notice(msg, 8e3);
    }
  }
  showOverdueSummary(overdue) {
    if (overdue.length === 1) {
      this.showFollowUpNotice(overdue[0], true);
    } else {
      const names = overdue.slice(0, 3).map((p) => p.name).join(", ");
      const extra = overdue.length > 3 ? ` +${overdue.length - 3} more` : "";
      new import_obsidian9.Notice(`${overdue.length} overdue follow-ups: ${names}${extra}`, 1e4);
    }
  }
  // Force a check (e.g., after vault opens or settings change)
  forceCheck() {
    this.check();
  }
};

// src/ai-enrichment.ts
var import_obsidian10 = require("obsidian");
var MAX_INTERACTION_LINES = 20;
function extractInteractionHistory(content) {
  const logStart = content.indexOf("## Interaction Log");
  if (logStart === -1)
    return "";
  const section = content.slice(logStart + "## Interaction Log".length);
  const lines = section.split("\n").filter((l) => l.trim().startsWith("- ")).slice(0, MAX_INTERACTION_LINES);
  return lines.join("\n");
}
async function callAnthropic(apiKey, prompt) {
  var _a, _b, _c;
  const response = await (0, import_obsidian10.requestUrl)({
    url: "https://api.anthropic.com/v1/messages",
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json"
    },
    body: JSON.stringify({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 512,
      messages: [{ role: "user", content: prompt }]
    })
  });
  if (response.status !== 200) {
    throw new Error(`Anthropic API error ${response.status}: ${response.text}`);
  }
  const data = response.json;
  return (_c = (_b = (_a = data.content) == null ? void 0 : _a[0]) == null ? void 0 : _b.text) != null ? _c : "";
}
async function callOpenAI(apiKey, model, prompt) {
  var _a, _b, _c, _d;
  const response = await (0, import_obsidian10.requestUrl)({
    url: "https://api.openai.com/v1/chat/completions",
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "content-type": "application/json"
    },
    body: JSON.stringify({
      model,
      max_tokens: 512,
      messages: [{ role: "user", content: prompt }]
    })
  });
  if (response.status !== 200) {
    throw new Error(`OpenAI API error ${response.status}: ${response.text}`);
  }
  const data = response.json;
  return (_d = (_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) != null ? _d : "";
}
function parseAISuggestion(raw) {
  var _a, _b, _c, _d, _e;
  const jsonMatch = (_a = raw.match(/```json\n?([\s\S]+?)\n?```/)) != null ? _a : raw.match(/\{[\s\S]*"action"[\s\S]*\}/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse((_b = jsonMatch[1]) != null ? _b : jsonMatch[0]);
      return {
        action: (_c = parsed.action) != null ? _c : raw,
        reasoning: (_d = parsed.reasoning) != null ? _d : "",
        suggestedMessage: (_e = parsed.suggested_message) != null ? _e : parsed.suggestedMessage
      };
    } catch (e) {
    }
  }
  return { action: raw.trim(), reasoning: "" };
}
async function getSuggestedFollowUp(person, personContent, settings) {
  const hasAnthropic = settings.aiProvider === "anthropic" && settings.anthropicApiKey;
  const hasOpenAI = settings.aiProvider === "openai" && settings.openaiApiKey;
  if (!hasAnthropic && !hasOpenAI) {
    throw new Error("No AI API key configured. Add one in Settings > Arcadia Connect > AI Enrichment.");
  }
  const history = extractInteractionHistory(personContent);
  const contextLines = [
    `Contact: ${person.name}`,
    person.organization ? `Organization: ${person.organization}` : "",
    person.role ? `Role: ${person.role}` : "",
    person.dealStage ? `Deal stage: ${person.dealStage}` : "",
    person.dealValue ? `Deal value: $${person.dealValue}` : "",
    person.lastContact ? `Last contact: ${person.lastContact}` : "",
    person.nextFollowUp ? `Scheduled follow-up: ${person.nextFollowUp}` : ""
  ].filter(Boolean);
  const prompt = `You are a CRM assistant. Based on this contact's profile and interaction history, suggest one specific, actionable follow-up action.

Contact profile:
${contextLines.join("\n")}

Recent interactions:
${history || "(No interactions logged yet)"}

Respond in this JSON format:
\`\`\`json
{
  "action": "Specific action to take (1-2 sentences)",
  "reasoning": "Why this action makes sense given the history",
  "suggested_message": "Optional: a short draft message or talking point"
}
\`\`\`

Keep the action concrete and immediate. Reference specific details from the history where possible.`;
  let raw;
  if (hasAnthropic) {
    raw = await callAnthropic(settings.anthropicApiKey, prompt);
  } else {
    raw = await callOpenAI(settings.openaiApiKey, settings.openaiModel, prompt);
  }
  return parseAISuggestion(raw);
}
var AISuggestionModal = class extends import_obsidian10.Modal {
  constructor(app, person, personManager, settings) {
    super(app);
    this.person = person;
    this.personManager = personManager;
    this.settings = settings;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("arcadia-ai-modal");
    contentEl.createEl("h3", { text: `AI Suggestion: ${this.person.name}` });
    const loadingEl = contentEl.createDiv({ cls: "arcadia-ai-loading", text: "Analyzing interaction history..." });
    try {
      const content = await this.app.vault.read(this.person.file);
      const suggestion = await getSuggestedFollowUp(this.person, content, this.settings);
      loadingEl.remove();
      const actionEl = contentEl.createDiv({ cls: "arcadia-ai-action" });
      actionEl.createDiv({ cls: "arcadia-ai-label", text: "Suggested action" });
      actionEl.createDiv({ cls: "arcadia-ai-value", text: suggestion.action });
      if (suggestion.reasoning) {
        const reasonEl = contentEl.createDiv({ cls: "arcadia-ai-reasoning" });
        reasonEl.createDiv({ cls: "arcadia-ai-label", text: "Reasoning" });
        reasonEl.createDiv({ cls: "arcadia-ai-value mod-muted", text: suggestion.reasoning });
      }
      if (suggestion.suggestedMessage) {
        const msgEl = contentEl.createDiv({ cls: "arcadia-ai-message" });
        msgEl.createDiv({ cls: "arcadia-ai-label", text: "Draft message" });
        const msgText = msgEl.createEl("textarea", {
          cls: "arcadia-ai-draft",
          attr: { rows: "4" }
        });
        msgText.value = suggestion.suggestedMessage;
      }
      const buttons = contentEl.createDiv({ cls: "arcadia-ai-buttons" });
      const appendBtn = buttons.createEl("button", {
        text: "Append to note",
        cls: "mod-cta"
      });
      appendBtn.addEventListener("click", () => {
        void (async () => {
          const noteContent = await this.app.vault.read(this.person.file);
          const today = new Date().toISOString().split("T")[0];
          const entry = `
---
**AI Suggestion** (${today})
${suggestion.action}${suggestion.suggestedMessage ? "\n\n*Draft:* " + suggestion.suggestedMessage : ""}
`;
          await this.app.vault.modify(this.person.file, noteContent + entry);
          new import_obsidian10.Notice("Suggestion appended to note.");
          this.close();
        })();
      });
      const closeBtn = buttons.createEl("button", { text: "Dismiss" });
      closeBtn.addEventListener("click", () => this.close());
    } catch (err) {
      loadingEl.remove();
      const errEl = contentEl.createDiv({ cls: "arcadia-ai-error" });
      errEl.textContent = err instanceof Error ? err.message : "Unknown error.";
      contentEl.createEl("button", { text: "Close" }).addEventListener("click", () => this.close());
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var ArcadiaConnectPlugin = class extends import_obsidian11.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.personManager = new PersonManager(this.app, this.settings.peopleFolder);
    this.mentionScanner = new MentionScanner(this.app, this.settings.peopleFolder);
    this.profileCard = new ProfileCard(this.app);
    this.followUpEngine = new FollowUpEngine(this.personManager);
    this.mentionPostProcessor = new MentionPostProcessor(
      this.app,
      this.personManager,
      this.settings,
      this.profileCard
    );
    this.addSettingTab(new ArcadiaConnectSettingTab(this.app, this));
    this.registerView(VIEW_TYPE_PEOPLE, (leaf) => {
      return new PeopleView(
        leaf,
        this.personManager,
        this.mentionScanner,
        this.profileCard
      );
    });
    this.registerView(VIEW_TYPE_TIMELINE, (leaf) => {
      return new TimelineView(leaf, this.personManager);
    });
    this.registerView(VIEW_TYPE_PIPELINE, (leaf) => {
      return new PipelineView(leaf, this.personManager);
    });
    this.registerEditorExtension(
      createMentionExtension(this.personManager, this.settings)
    );
    this.registerMarkdownPostProcessor(
      this.mentionPostProcessor.getProcessor()
    );
    this.addRibbonIcon("users", "People Panel", () => {
      void this.activatePeopleView();
    });
    this.addRibbonIcon("history", "Interaction Timeline", () => {
      void this.activateView(VIEW_TYPE_TIMELINE);
    });
    this.addRibbonIcon("kanban-square", "Deal Pipeline", () => {
      void this.activateView(VIEW_TYPE_PIPELINE);
    });
    this.addCommand({
      id: "open-people-panel",
      name: "Open People Panel",
      callback: () => {
        void this.activatePeopleView();
      }
    });
    this.addCommand({
      id: "create-person-note",
      name: "Create Person Note",
      callback: async () => {
        await this.createPersonNoteCommand();
      }
    });
    this.addCommand({
      id: "mention-person",
      name: "Mention Person",
      editorCallback: (editor) => {
        editor.replaceSelection(this.settings.triggerChar || "@");
      }
    });
    this.addCommand({
      id: "open-timeline",
      name: "Open Interaction Timeline",
      callback: () => {
        void this.activateView(VIEW_TYPE_TIMELINE);
      }
    });
    this.addCommand({
      id: "open-pipeline",
      name: "Open Deal Pipeline",
      callback: () => {
        void this.activateView(VIEW_TYPE_PIPELINE);
      }
    });
    this.addCommand({
      id: "log-interaction",
      name: "Log Interaction",
      callback: () => {
        new InteractionLoggerModal(this.app, this.personManager, null, () => {
          this.refreshPeopleView();
        }).open();
      }
    });
    this.addCommand({
      id: "ai-suggest-followup",
      name: "AI: Suggest Follow-up for Active Contact",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file)
          return false;
        const person = this.personManager.getAllPeople().find((p) => p.file.path === file.path);
        if (!person)
          return false;
        if (!checking) {
          new AISuggestionModal(this.app, person, this.personManager, this.settings).open();
        }
        return true;
      }
    });
    this.app.workspace.onLayoutReady(() => {
      this.personManager.initialize();
      void this.mentionScanner.buildIndex();
      this.followUpEngine.start();
    });
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (this.personManager.isInPeopleFolder(file)) {
          this.personManager.updatePerson(file);
        }
        this.mentionScanner.onFileChange(file);
        this.refreshPeopleView();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian11.TFile) {
          if (this.personManager.isInPeopleFolder(file)) {
            this.personManager.removePerson(file);
          }
          this.mentionScanner.onFileDelete(file);
          this.refreshPeopleView();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian11.TFile && this.personManager.isInPeopleFolder(file)) {
          setTimeout(() => {
            this.personManager.updatePerson(file);
            this.refreshPeopleView();
          }, 500);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian11.TFile) {
          setTimeout(() => {
            this.personManager.scanPeopleFolder();
            void this.mentionScanner.buildIndex();
            this.refreshPeopleView();
          }, 500);
        }
      })
    );
  }
  onunload() {
    this.followUpEngine.stop();
    this.profileCard.destroy();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.personManager.setPeopleFolder(this.settings.peopleFolder);
    this.mentionScanner.setPeopleFolder(this.settings.peopleFolder);
    this.personManager.scanPeopleFolder();
    void this.mentionScanner.buildIndex();
    this.refreshPeopleView();
  }
  async activatePeopleView() {
    return this.activateView(VIEW_TYPE_PEOPLE);
  }
  async activateView(viewType) {
    const existing = this.app.workspace.getLeavesOfType(viewType);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({ type: viewType, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  refreshPeopleView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_PEOPLE);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof PeopleView) {
        view.renderList();
      }
    }
  }
  async createPersonNoteCommand() {
    const name = await this.promptForName();
    if (!name)
      return;
    const file = await this.personManager.createPersonNote(name);
    await this.app.workspace.openLinkText(file.path, "", false);
  }
  promptForName() {
    return new Promise((resolve) => {
      const modal = document.createElement("div");
      modal.className = "arcadia-connect-name-modal";
      const overlay = document.createElement("div");
      overlay.className = "arcadia-connect-modal-overlay";
      const content = document.createElement("div");
      content.className = "arcadia-connect-modal-content";
      const label = document.createElement("label");
      label.textContent = "Person name:";
      content.appendChild(label);
      const input = document.createElement("input");
      input.type = "text";
      input.className = "arcadia-connect-modal-input";
      input.placeholder = "Full Name";
      content.appendChild(input);
      const buttons = document.createElement("div");
      buttons.className = "arcadia-connect-modal-buttons";
      const cancelBtn = document.createElement("button");
      cancelBtn.textContent = "Cancel";
      cancelBtn.addEventListener("click", () => {
        modal.remove();
        resolve(null);
      });
      buttons.appendChild(cancelBtn);
      const createBtn = document.createElement("button");
      createBtn.textContent = "Create";
      createBtn.className = "mod-cta";
      createBtn.addEventListener("click", () => {
        const value = input.value.trim();
        modal.remove();
        resolve(value || null);
      });
      buttons.appendChild(createBtn);
      content.appendChild(buttons);
      modal.appendChild(overlay);
      modal.appendChild(content);
      document.body.appendChild(modal);
      overlay.addEventListener("click", () => {
        modal.remove();
        resolve(null);
      });
      input.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          const value = input.value.trim();
          modal.remove();
          resolve(value || null);
        }
        if (e.key === "Escape") {
          modal.remove();
          resolve(null);
        }
      });
      input.focus();
    });
  }
};
